README.md
I had to go to [context.rb](https://github.com/fnando/browser/blob/master/lib/browser/middleware/context.rb) to find this, so perhaps it's worth mentioning in the README?
=> Mention middleware request accessor in README

browser.gemspec
I was trying to determine the licenses for my dependencies. I found that the RubyGems API will return the license, but only if it is specified in your gemspec file.
=> Add license to gemspec

README.md
As of 6437455a6, Microsoft Edge is considered a "modern" browser by this gem.
=> Add MS Edge to list of "modern" browsers in readme

README.md, browser.gemspec, lib/browser.rb, lib/browser/methods/platform.rb, test/ua.yml, test/unit/ios_app_test.rb, test/unit/ios_test.rb
The user agent from an app webview doesn't include the `Safari/:version` part. We can possibly detect if request is coming from an app's webview if it doesn't include this string.
Here's the user agent from Safari: 
```
Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H141 Safari/600.1.4
```
And here's the user agent from iOS webview:
```
Mozilla/5.0 (iPhone; CPU iPhone OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141
```
=> Detect iOS apps webview. Close #179.

.travis.yml, gemfiles/rails4.gemfile
Add gemfile for Rails 4, bump 2.2 to 2.2.2, prevent Rails 5 test on 2.1.
=> Fix Travis tests for Rails 5

lib/browser/action_controller.rb
In controllers inherited from `ActionController:API`, we don't have available the `helper_method` method.
=> Conditional use of helper_method in ActionController

.gitignore, README.md, lib/browser/base.rb, lib/browser/browser.rb, lib/browser/electron.rb, test/ua.yml, test/unit/electron_test.rb
`Electron` based apps are currently marked as `Chrome` (which is correct), but there needs to be a way to tell them apart.
=> Add support for Electron Framework

lib/browser/opera.rb, test/ua.yml, test/unit/android_test.rb, test/unit/chrome_test.rb
e.g. for user agents like '...Android 8.0.0; Pixel Build/OPR6...'.
=> Detect Opera by checking for 'OPR/' instead of 'OPR' so Android Oreo is not falsely detected as Opera.

lib/browser/rails.rb
Currently, users cannot configure ActionController in initializers when
they use browser gem because browser gem loads ActionController::Base
too early.
=> Lazy load ActionController::Base

CHANGELOG.md, lib/browser/instagram.rb, test/ua.yml, test/unit/instagram_test.rb
While using this, we came across a user agent that took the form:
Instagram/182257141 CFNetwork/1107.1 Darwin/19.0.0
This is matched by the instagram matcher, but can't be parsed because it
assumes that there will be a space following Instagram. This updates it
to look for a space or a slash.
=> Fix detection of instagram browser

CHANGELOG.md, lib/browser/device.rb, lib/browser/device/android.rb, lib/browser/device/tv.rb, test/unit/device_test.rb
Close #231.
The biggest issue here is which id should be returned. We can't dynamically generate it because we need a reliable value.
=> Get device name from android devices.

CHANGELOG.md, lib/browser/instagram.rb, lib/browser/snapchat.rb
All other browsers have these, but instagram and snapchat do not, and this has proven to be very error-prone.
=> Add fallback versions for instagram and snapchat

.rubocop.yml, CHANGELOG.md, lib/browser/platform/ios.rb, test/ua.yml, test/unit/ios_test.rb
iOS 10+ is always detected as `0` because the regex does not match two-digit numbers.
This is a regression introduced in https://github.com/fnando/browser/commit/2eca1f04e20b1f740b5ec773d52bdaa3ed7ffbc9#diff-9d41eb017f6992f4da43a01f665aa17dR7 (version 2.7.0)
=> Fix iOS 10+ version detection

.rubocop.yml, CHANGELOG.md, lib/browser/browser.rb, lib/browser/device.rb, lib/browser/qq.rb, lib/browser/rails.rb, test/ua.yml, test/unit/chrome_test.rb
Tests added. This user agent was misidentified as:
chrome?: true
name: "QQ Browser"
version: 0
full_version: 0.0
When it is actually Chrome 78 on Android 10 on Google Pixel 2
Fixed QQ browser check. Instead of `QQ` it needs to include either `QQ/` or `QQBrowser`
=> [FIX] misidentification of android build QQ1A as QQ browser

.bundle/config, .gitignore
This directory gets included in the generated gems and is breaking some automation of ours. One option would be to exclude it in the gemspec, but bundler [explicitly says the directory should not be committed](https://bundler.io/v2.0/guides/bundler_sharing.html) in the first place:
> Do not check in the .bundle directory or any of the files inside it. Those files are specific to each particular machine and are used to persist installation options between runs of the bundle install command.
So even though the automation is specific to us, it seems like a best practice to adopt?
=> Remove the .bundle directory

browser.gemspec
For a nice “Changelog” link in the https://rubygems.org/gems/browser sidebar.
=> Add changelog to gemspec

browser.gemspec
This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/browser or some tools or APIs that use the gem's metadata.
=> GitHub is HTTPS by default

lib/browser/safari.rb, test/unit/samsung_browser_test.rb
This PR fixes the problem where `browser.safari?` would return `true` when the client has Samsung Browser user agent.
=> Samsung Browser should not be identified as Safari

README.md
Back in #449, Browser gem introduced support for Samsung Browser. However, it seems like this method has never been added to the README.md.
This PR adds `#samsung_browser?` to the list of available methods in the README.md.
=> Add #samsung_browser? to README.md

browser.gemspec
With the branch name change from master -> main, the changelog URI was pointing to an older version that didn't show the latest version's changes.
I found this when clicking on the changelog link on rubygems.
=> update changelog_uri in gemspec

CHANGELOG.md, bots.yml, test/ua_bots.yml
Adds [AppSignal](https://docs.appsignal.com/uptime-monitoring/setup.html#user-agent) and [Checkly](https://www.checklyhq.com/docs/monitoring/allowlisting/#default-checkly-user-agent) bot monitors to known bots list
=> Add AppSignal and Checkly bots

CHANGELOG.md, README.md, lib/browser/base.rb, lib/browser/browser.rb, lib/browser/epiphany.rb, lib/browser/safari.rb, test/ua.yml, test/unit/epiphany_test.rb
=> Add epiphany (gnome web) browser detection.

browser.gemspec
I noticed that the project already has a FUNDING.yml. This PR adds the `funding_uri` to your gemspec to help increase visibility using the `bundle fund` command in Bundler.
=> Add funding_uri to gemspec
