fnando/browser

lib/browser/methods/platform.rb, test/browser_spec.rb, test/ua.yml
Add three new methods for windows platform detection:
* `windows8_1?`
* `windows_wow64?`
* `windows_x64_inclusive?`
=> Add additional windows platform methods

README.md
Just a indexing in the phrase "You can define your *your* rules.".
The correct would be "You can define your *own* rules."
BTW, thanks for the awesome gem :gem: !
=> Indexing README.md

lib/browser.rb, test/browser_spec.rb
Hey @fnando
Just added Microsoft edge to modern browser list so that it doesn't get redirected due to upgrade middleware. 
Please review and merge.
=> Microsoft Edge: Add microsoft edge to modern browser list

README.md
=> Changes misleading example for modern rules

README.md
Last change from spec to test had consequences :P
=> Update README link to test file

languages.yml
There are 2 same keys with different value.
=> Remove duplication in favour of "Scots Gaelic"

Rakefile, lib/browser/detect_version.rb, test/ua.yml, test/unit/android_test.rb
=> Fix issue with version detection when no actual version is provided.

README.md, lib/browser.rb, lib/browser/base.rb, lib/browser/micro_messenger.rb, test/ua.yml, test/unit/micro_messenger_test.rb
This pr has added the MicroMessenger(WeChat) detection.
=> Added MicroMessenger detection

lib/browser.rb, lib/browser/qq.rb, test/ua.yml, test/unit/qq_test.rb
QQ is another strange browser like wechat.
Now let's detect it
=> Add QQ Browser support

lib/browser/accept_language.rb, test/unit/accept_language_test.rb
This deals with conflicts of #285.
=> Format accept_language components.

README.md
=> fix to svg travis badge

browser.gemspec, lib/browser/accept_language.rb, test/unit/accept_language_test.rb
=> Fix accept-language sorting

CHANGELOG.md, bots.yml, test/ua_bots.yml
=> Add ScoutURLMonitor to the bot list.

CHANGELOG.md
=> Update CHANGELOG.md Unreleased -> 2.7.0

CHANGELOG.md
Thanks for releasing v2.7.1. It seems nice update for me!
But change log section was not tagged.
https://github.com/fnando/browser/compare/v2.7.0...v2.7.1#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR6
=> update changelog section for v2.7.1

CHANGELOG.md, lib/browser/browser.rb
=> Fix MS Edge detection as modern browser for current release.

README.md
This shows the functionality of the version check a bit more in details.
=> Use version string in modern browser example

.rubocop.yml, CHANGELOG.md, lib/browser/base.rb, lib/browser/browser.rb, lib/browser/chrome.rb, lib/browser/samsung_browser.rb, test/ua.yml, test/unit/samsung_browser_test.rb, test/unit/samsung_test.rb
Currently, the Samsung Browser gets incorrectly recognized as Chrome. This PR fixes that.
=> Add Samsung Browser.

CHANGELOG.md, lib/browser/browser.rb, test/ua.yml, test/unit/micro_messenger_test.rb
=> Fix MicroMessenger detection on Android, close #452

CHANGELOG.md, lib/browser/edge.rb, test/ua.yml, test/unit/edge_test.rb
=> Fix Microsoft Edge detection on iOS & Android

CHANGELOG.md, lib/browser/base.rb, lib/browser/browser.rb, lib/browser/chrome.rb, lib/browser/huawei_browser.rb, lib/browser/safari.rb, test/ua.yml, test/unit/huawei_browser_test.rb
=> Add Huawei Browser detection

lib/browser/safari.rb, test/unit/opera_test.rb
=> Opera Browser should not be identified as Safari

CHANGELOG.md, lib/browser/safari.rb, test/unit/alipay_test.rb
=> Don't recognize Alipay also as Safari

CHANGELOG.md, README.md, lib/browser/base.rb, lib/browser/browser.rb, test/browser_test.rb
=> Set size limit for user agent and accept language.

CHANGELOG.md, README.md, lib/browser/device.rb, lib/browser/device/samsung.rb, samsung.yml, test/ua.yml, test/unit/device_test.rb
=> Detect Samsung devices.

.github/FUNDING.yml, CHANGELOG.md, README.md, lib/browser/base.rb, lib/browser/browser.rb, lib/browser/chrome.rb, lib/browser/edge.rb, test/browser_test.rb, test/test_helper.rb, test/unit/android_app_test.rb, test/unit/android_test.rb, test/unit/blackberry_test.rb, test/unit/bots_test.rb, test/unit/chrome_test.rb, test/unit/device_test.rb, test/unit/edge_test.rb, test/unit/electron_test.rb, test/unit/generic_test.rb, test/unit/internet_explorer_test.rb, test/unit/ios_app_test.rb, test/unit/ios_test.rb, test/unit/meta_test.rb, test/unit/platform_test.rb, test/unit/proxy_test.rb, test/unit/safari_test.rb
=> Add `Browser::Base#chromium_based?`.
